name: Build check

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*" # We don't want this to run on release
  pull_request:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2019
    env:
      BOOST_ROOT: C:/tools/boost/x86_64
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        shell: powershell
        id: setup
        run: |
          $os="windows"
          $ccx_version="${{ github.sha }}".SubString(0,7)
          $release_name="ccx-cli-$os-dev-$ccx_version"
          echo "::set-output name=release_name::${release_name}"

      - name: Install msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dependencies
        shell: powershell
        run: |
          echo "${env:BOOST_ROOT}"
          $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
          (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
          Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=${env:BOOST_ROOT}"

      - name: Build
        shell: powershell
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
          msbuild concealX.sln /p:Configuration=Release /m:2

      - name: Prepare release
        shell: powershell
        run: |
          mkdir build/bin
          mv build/src/Release/conceald.exe build/bin
          mv build/src/Release/concealwallet.exe build/bin
          mv build/src/Release/optimizer.exe build/bin
          mv build/src/Release/walletd.exe build/bin
          mv build/tests/Release/*_tests.exe build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: core_tests
        shell: powershell
        run: |
          cd build/bin
          ./core_tests.exe --generate_and_play_test_data

      - name: difficulty_tests
        shell: powershell
        run: |
          cp tests/Difficulty/data.txt build/bin
          cd build/bin
          ./difficulty_tests.exe data.txt

      - name: performance_tests
        shell: powershell
        run: |
          cd build/bin
          ./performance_tests.exe

  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=ubuntu-18.04
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake gcc g++ libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DSTATIC=ON
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin
          mv build/tests/*_tests build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: core_tests
        run: |
          cd build/bin
          ./core_tests --generate_and_play_test_data

      - name: difficulty_tests
        run: |
          cp tests/Difficulty/data.txt build/bin
          cd build/bin
          ./difficulty_tests data.txt

      - name: performance_tests
        run: |
          cd build/bin
          ./performance_tests

      - name: system_tests
        run: |
          cd build/bin
          ./system_tests

  build-ubuntu20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=ubuntu-20.04
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake gcc g++ libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DSTATIC=ON
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin
          mv build/tests/*_tests build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: core_tests
        run: |
          cd build/bin
          ./core_tests --generate_and_play_test_data

      - name: difficulty_tests
        run: |
          cp tests/Difficulty/data.txt build/bin
          cd build/bin
          ./difficulty_tests data.txt

      - name: performance_tests
        run: |
          cd build/bin
          ./performance_tests

      - name: system_tests
        run: |
          cd build/bin
          ./system_tests

  build-ubuntu20-clang:
    name: Ubuntu 20.04 clang
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=ubuntu-20.04-clang
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake clang libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          CC=clang CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Release  -DBUILD_TESTS=ON -DSTATIC=ON
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin
          mv build/tests/*_tests build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: core_tests
        run: |
          cd build/bin
          ./core_tests --generate_and_play_test_data

      - name: difficulty_tests
        run: |
          cp tests/Difficulty/data.txt build/bin
          cd build/bin
          ./difficulty_tests data.txt

      - name: performance_tests
        run: |
          cd build/bin
          ./performance_tests

      - name: system_tests
        run: |
          cd build/bin
          ./system_tests

  build-macos11:
    name: macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=macos-11
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          brew install boost

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DSTATIC=ON
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin
          mv build/tests/*_tests build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: core_tests
        run: |
          cd build/bin
          ./core_tests --generate_and_play_test_data

      - name: difficulty_tests
        run: |
          cp tests/Difficulty/data.txt build/bin
          cd build/bin
          ./difficulty_tests data.txt

      - name: performance_tests
        run: |
          cd build/bin
          ./performance_tests
